language: cpp
compiler: gcc
dist: trusty

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo apt-get install libgtest0 libgtest-dev
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev
  - sudo apt-get install qt5-default qttools5-dev-tools

before_script:
  - sudo apt-get install doxygen -y
  - sudo apt-get install graphviz -y
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list

script:
  - qmake -project
  - qmake GraphicBalls_main
  - make
  - doxygen doxygen.dox

#deploy:
#  - provider: pages
#    skip-cleanup: true
#    local_dir: /html
#    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
#    keep-history: true
#    on:
#      branch: master
